---

- name: Ensure that prerequisites are installed.
  apt:
    name: "{{ item }}"
    state: present
  
  loop: "{{ postgresql_prerequisites }}"
  
- name: Import the repository signing key.
  apt_key:
    url: "{{ postgresql_apt_key }}"
    state: present
    keyring: "{{ postgres_apt_keyring_path }}"

- name: Add PostgreSQL repository.
  apt_repository:
    repo: "{{ postgresql_repo_url }}"
    state: present
    filename: pgdg
    update_cache: yes


